# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('usage', models.TextField()),
                ('op_time', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('pdis', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
